const HomePage = () => {
  return (
    <div className="HomePage">
        <h3>hompage</h3>
        <p>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            a<br/>
            
            
            
            
        </p>
    </div>
  );
};

export default HomePage;
